# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "precise64"
  config.vm.host_name = "dev"
  config.vm.forward_port 8000, 8000
  config.vm.share_folder "project", "/mnt/project", "./"
  config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/project", "1"]
  config.vm.provision :shell, :path => "vagrant.sh"
end
